blueprint:
  name: Zigbee2MQTT - Tuya 4-Button Scene Switch (TS004F)
  description: Automate your Tuya 4-Button Scene Switch via Zigbee2MQTT (TS004F).
  domain: automation
  input:
    switch:
      name: Tuya 4-Button Scene Switch (TS004F)
      description: Tuya 4-Button Scene Switch to use (TS004F)
      selector:
        entity:
          integration: mqtt
          domain: sensor
    button_one_short_press:
      name: Single Press - Button 1
      description: Action to run on button 1 (lower-left) single press
      default: []
      selector:
        action: {}
    button_two_short_press:
      name: Single Press - Button 2
      description: Action to run on button 2 (lower-right) single press
      default: []
      selector:
        action: {}
    button_three_short_press:
      name: Single Press - Button 3
      description: Action to run on button 3 (upper-right) single press
      default: []
      selector:
        action: {}
    button_four_short_press:
      name: Single Press - Button 4
      description: Action to run on button 4 (upper-left) single press
      default: []
      selector:
        action: {}
source_url: https://github.com/aitoralonso/ha-blueprint/blob/main/blueprints/tuya/tuya_4button_scene_switch_z2m.yaml
mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input "switch"
  attribute: action
action:
- variables:
    command: "{{ trigger.to_state.state }}"
- choose:
  - conditions: 
    - "{{ command == 'on' }}"
    sequence: !input "button_one_short_press"
  - conditions: 
    - "{{ command == 'off' }}"
    sequence: !input "button_two_short_press"
  - conditions: 
    - "{{ command == 'brightness_step_up' }}"
    sequence: !input "button_three_short_press"
  - conditions: 
    - "{{ command == 'brightness_step_down' }}"
    sequence: !input "button_four_short_press"
